### ISSUE TITLE
Rspec multiple runs because of exit when testing forked process

### ISSUE THREAD

**Issue by SephVelut** [rspec/rspec-core#2058]
I'm having difficulties testing code that happens to fork processes.

```
# code under test
exit if fork
Process.setsid
exit if fork
```

Will cause rspec to run more than once because of the `Kernel#exit`. Using `exit!` changes this behavior. Any proposed rspec solutions I'm missing?

Related #1164 & #977 

I have rspec installed with bundler. Running it via `rspec` command. Fresh install, no changed to `spec_helper`.

**Comment by myronmarston** [comment]
In RSpec 3, we avoid the `at_exit` hook unless it's absolutely necessary (e.g. due to the user trying to run things through `ruby path/to/spec.rb` instead the `rspec` command), so I would not expect a problem.  What version of RSpec are you using?  How are you running RSpec?  Can you provide an executable example demonstrating the problem?

**Comment by SephVelut** [comment]
https://github.com/SephVelut/rspec_runs_again_on_exit

I setup a repo with an executable demonstration. The code is bare minimum and I have commented the areas of interest. When attempting to create a daemon process on unix, a second fork is spawned to prevent the daemon from acquiring a controlling terminal. Rspec runs once for the parent of the daemon when the parent eventually returns. Rspec then runs again for the forked process when it exists. This might not even be a technical problem, but it is a `gothcha` when forking and exiting processes that originated from a spec.

I'm avoiding the issue right now by catching `SystemExit` and exiting from rspec quietly. 

```
it 'spec' do
   begin
       expect(Test.new.spawn).to eq(true)
   rescue SystemExit
       exit!
    end
end
```

**Comment by myronmarston** [comment]
Addressed in #2058.

**Comment by SephVelut** [comment]
Don't you mean #2063?

**Comment by myronmarston** [comment]
Yes. Whoops!

**Comment by flushentitypacket** [comment]
I seem to be having this same issue, even on rspec-core 3.4.1. Anyone else still experiencing this?

**Comment by flushentitypacket** [comment]
Update: Seems fixed on rspec-core 3.4.0, but possibly regressed for 3.4.1
