### ISSUE TITLE
Feature request: Pass `let` variables as arguments to `shared_examples` using `shared_expectations`

### ISSUE THREAD

**Issue by francktrouillez** [rspec/rspec-core#3115]
### Subject of the issue
Currently, there's no built-in way to use `shared_examples` with `let` variables as arguments. I've been a big fan of `let` variables and I use them a lot in my tests. I'd like to be able to use them in `shared_examples` as well, since both features are super useful in my opinion, but there's currently some friction when trying to use them simultaneously.

In this issue, I'm proposing a new feature called `shared_expectations` that would allow us to use `let` variables and (kind of) shared examples at the same time with less friction.

#### What situation are we talking about?

I'm taking about situations like this:
```ruby
RSpec.shared_examples "a foo" do |bar|
  it { is_expected.to eq(bar) }
end
```

Currently, if I want to use this shared example with the argument `bar` defined using a `let`, I have to either:
- Avoid using arguments for the shared example and redefine `let` variables in the context of the example group, or make sure the previous `let` definitions match what's used inside the shared example
  ```ruby
  RSpec.shared_examples "a foo without argument" do
    it { is_expected.to eq(bar) }
  end

  RSpec.describe "Baz" do
    subject { Baz.foo }
    let(:baz) { "baz" }

    context "when bar is not defined yet" do
      it_behaves_like "a foo without argument" do
        let(:bar) { baz }
      end
    end

    context "when bar is already defined" do
      let(:bar) { baz }

      it_behaves_like "a foo without argument"
    end
  end
  ```
- Pass a symbol/string to the shared example and use meta-programming to access the `let` variables
  ```ruby
  RSpec.shared_examples "a foo with symbol argument" do |bar_symbol|
    it { is_expected.to eq(send(bar_symbol)) }
  end

  RSpec.describe "Baz" do
    subject { Baz.foo }
    let(:baz) { "baz" }

    it_behaves_like "a foo", :baz
  end
  ```

There probably exists other workarounds, but these are the 2 that I've used in the past. I'd like to be able to use `let` variables directly in the shared example, without having to redefine them or use meta-programming (or any other "unnatural" workarounds).

You can see more discussions about this topic in the following issue:
- https://github.com/rspec/rspec-core/issues/2424

#### What could be an alternative?

In my opinion, the "obvious" solution would be to find a way to pass `let` variables to `shared_examples` directly. However, it can raise concerns about the nature of `let`, in the sense that `let` are meant to be lazily evaluated during examples, while `shared_examples` are not examples themselves (besides the implementation complexity).

For that reason, I thought about an alternative, that would introduce the notion of `shared_expectations`. This would be a new feature that would be similar to `shared_examples`, but would be used inside the `it` block, instead of the `context`/`describe` block. This way, we could use `let` variables directly in the shared expectations.

The exposed API would look like this:
```ruby
RSpec.shared_expectations "a foo" do |bar|
  is_expected.to eq(bar)
end

RSpec.describe "Baz" do
  subject { Baz.foo }
  let(:baz) { "baz" }

  it { behaves_like "a foo", baz }
end
```

As you see, the idea would be to use `shared_expectations`, and call them using `behaves_like` (instead of using `shared_examples` and `it_behaves_like`). This way, we could use `let` variables directly in the shared expectations, while keeping the descriptive aspect of RSpec that I love.

###### What would the implementation look like?
I'm not familiar enough with the RSpec codebase, but a naive approach would be to have few methods that would be called when `shared_expectations` are defined and called. These methods would be similar to the ones used for `shared_examples`, but would be called in the context of the `it` block.

```ruby
module SharedExpectations
  def self.registry
    @registry ||= {}
  end

  def behaves_like(name, *args)
    instance_exec(*args, &SharedExpectations.registry[name])
  end
end

module RSpec
  def self.shared_expectations(name, &block)
    SharedExpectations.registry[name] = block
  end
end

RSpec.configure do |config|
  config.include SharedExpectations
end
```

Once again, this is a super naive approach, not meant to be used as is in the RSpec codebase, but hopefully it gives you an idea of what the API could look like.

### Your environment
* Ruby version: 3.2.3
* rspec-core version: 3.13.0

#### Current situation

```ruby
# frozen_string_literal: true

begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"

  gem "rspec", "3.13.0" # Activate the gem and version you are reporting the issue against.
end

puts "Ruby version is: #{RUBY_VERSION}"
puts "RSpec version is: #{RSpec::Version::STRING}"
require 'rspec/autorun'

class Baz; def self.foo; "baz"; end; end

RSpec.shared_examples "a foo without argument" do
  it { is_expected.to eq(bar) }
end

RSpec.shared_examples "a foo with symbol argument" do |bar_symbol|
  it { is_expected.to eq(send(bar_symbol)) }
end

RSpec.describe "Baz" do
  subject { Baz.foo }
  let(:baz) { "baz" }

  context "when bar is not defined yet" do
    it_behaves_like "a foo without argument" do
      let(:bar) { baz }
    end
  end

  context "when bar is already defined" do
    let(:bar) { baz }

    it_behaves_like "a foo without argument"
  end

  it_behaves_like "a foo with symbol argument", :baz
end
```

#### Proposed situation
(implementation-wise, super naive approach not following any RSpec conventions and that probably have flaws, but that shows what the API could look like)

```ruby
# frozen_string_literal: true

begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"

  gem "rspec", "3.13.0" # Activate the gem and version you are reporting the issue against.
end

puts "Ruby version is: #{RUBY_VERSION}"
puts "RSpec version is: #{RSpec::Version::STRING}"
require 'rspec/autorun'

class Baz; def self.foo; "baz"; end; end

# Naively monkey patch RSpec to add the new feature

module SharedExpectations
  def self.registry
    @registry ||= {}
  end

  def behaves_like(name, *args)
    instance_exec(*args, &SharedExpectations.registry[name])
  end
end

module RSpec
  def self.shared_expectations(name, &block)
    SharedExpectations.registry[name] = block
  end
end

RSpec.configure do |config|
  config.include SharedExpectations
end

# Define shared expectations

RSpec.shared_expectations "a foo" do |bar|
  is_expected.to eq(bar)
end

# Use shared expectations

RSpec.describe "Baz" do
  subject { Baz.foo }
  let(:baz) { "baz" }

  it { behaves_like "a foo", baz }
end
```

### Implementation
**IF** this whole idea makes sense, I'd be happy to help with the implementation, even though I'm not familiar with the RSpec codebase. I'm a big fan of RSpec and I'd love to contribute to the project.

### Closing thoughts

I hope this issue makes sense and that it's not too confusing. I'm happy to provide more information if needed. I'm also happy to discuss the idea further, if you think it's worth it.

Of course, if I'm missing something and there's already a more "natural" way to use `let` variables in `shared_examples`, I'd be happy to know about it! Also, if you think this idea is against the philosophy of RSpec, please let me know!

Thanks for your time and for the amazing work you're doing with RSpec!

**Comment by pirj** [comment]
I recall doing it this way:

```ruby
RSpec.shared_examples "a foo" do |bar|
  let(:bar) { bar } # yuck!

  it { expect(bar).to eq("bar") }
end

RSpec.describe "bar" do
  it_behaves_like "a foo", "bar"
end
```

But now when I try it, it works without the `let(:bar) { bar }`, too:

```ruby
RSpec.shared_examples "a foo" do |bar|
  it { expect(bar).to eq("bar") }
end

RSpec.describe "bar" do
  it_behaves_like "a foo", "bar"
end
```

Is this something you're after?

**Comment by francktrouillez** [comment]
@pirj 
> I recall doing it this way:
> 
> ```ruby
> RSpec.shared_examples "a foo" do |bar|
>   let(:bar) { bar } # yuck!
> 
>   it { expect(bar).to eq("bar") }
> end
> 
> RSpec.describe "bar" do
>   it_behaves_like "a foo", "bar"
> end
> ```
> 
> But now when I try it, it works without the `let(:bar) { bar }`, too:
> 
> ```ruby
> RSpec.shared_examples "a foo" do |bar|
>   it { expect(bar).to eq("bar") }
> end
> 
> RSpec.describe "bar" do
>   it_behaves_like "a foo", "bar"
> end
> ```
> 
> Is this something you're after?

Thanks for the answer!

From my understanding, I'm trying to solve another problem, which is when the `let` isn't defined in the shared example itself, and when the arguments of the shared example are values that are defined using `let`.

Using your example, I'd like to somehow pass the `bar` value defined in the `let` block to the shared example, without having to redefine it in the context of the example group.

```ruby
RSpec.shared_examples "a foo" do |bar|
  it { expect(bar).to eq("bar") }
end

RSpec.describe "bar" do
  context "when bar is 'bar'" do
    let(:bar) { "bar" }

    it_behaves_like "a foo", bar
  end

  context "when bar is 'not bar'" do
    let(:bar) { "not bar" }

    it_behaves_like "a foo", bar # this would be a failing example
  end
end
```

Right now, this wouldn't work/execute, because I'm trying to pass `bar` as an argument to the shared example, but it's not defined in the shared example itself.

_Note_: In this specific example, this could be solved by directly passing the strings to the shared example (the same way you did in your examples), but I'm trying to solve a more general problem, where the `let` variables are used in a more complex way. You could imagine a value that is calculated using a `let` block, for example. Like, the below example with a random number, but it could be the same with a record created using FactoryBot, etc.

```ruby
RSpec.shared_examples "a number greater than 0" do |number|
  it { expect(number).to be > 0 }
end

RSpec.shared_examples "a number lower than 10" do |number|
  it { expect(number).to be < 10 }
end

RSpec.describe "a roulette" do
  let(:random_number) { rand(1...10) }

  it_behaves_like "a number greater than 0", random_number
  it_behaves_like "a number lower than 10", random_number
end
```

Once again, this currently wouldn't work/execute, because `random_number` is not defined in the shared example itself, but instead in a `let` in the context defining the shared examples.

Let me know if I've misunderstood your answer, or if you have any other ideas on how to solve this problem! Thank you very much for your help!

**Comment by pirj** [comment]
```ruby
RSpec.describe "a roulette" do
  let(:random_number) { rand(1...10) }

  it_behaves_like "a number greater than 0", random_number
  it_behaves_like "a number lower than 10", random_number
end
```

won’t work as it’s not supposed to. And you don’t need to pass it, it’s already available in the shared example.

One important thing to understand here is the difference between the example group context and the example context. Variables defined with ‘let’ are available in the latter. The block that defines them runs in the former. You can think about this as class level and instance level, because they are like this internally.

I’m not convinced that we should change this in any way.

**Comment by francktrouillez** [comment]
@pirj

Thanks for the answer!

I'm probably missing something, but I don't think the problem I'm trying to solve is well addressed by your answer.

> ```ruby
> RSpec.describe "a roulette" do
>   let(:random_number) { rand(1...10) }
>
>   it_behaves_like "a number greater than 0", random_number
>   it_behaves_like "a number lower than 10", random_number
> end
> ```
> won’t work as it’s not supposed to. And you don’t need to pass it, it’s already available in the shared example.
>
> One important thing to understand here is the difference between the example group context and the example context. Variables defined with ‘let’ are available in the latter. The block that defines them runs in the former. You can think about this as class level and instance level, because they are like this internally.
>
> I’m not convinced that we should change this in any way.

Indeed, and I agree with this, which is why I'm trying to use something different than `shared_examples` to solve this problem (see issue body for more details). I don't want to change what meaning and semantics `let` and `shared_examples` have in RSpec, but I'm trying to find a way to pass the reference to `let` variables to some shared parts of the tests (in my case, it would be `shared_expectations`, but it could be anything that would help me achieve this.).

I'm trying to solve different cases.

For instance, in this example, I'm trying to pass the `random_number` value to the shared example, but it's not defined in the shared example itself.
```ruby
RSpec.shared_examples "a number greater than 0" do |number|
  it { expect(number).to be > 0 }
end

RSpec.describe "a roulette" do
  let(:random_number) { rand(1...10) }

  it_behaves_like "a number greater than 0", random_number
end
```

(this obviously wouldn't work, since it's exactly the type of problem I'm trying to solve)

What I should do with the current state is something like this for instance:
```ruby
RSpec.shared_examples "a random number greater than 0" do
  it { expect(random_number).to be > 0 }
end

RSpec.describe "a roulette" do
  let(:random_number) { rand(1...10) }

  it_behaves_like "a random number greater than 0"
end
```

Now, what if I'm trying to share this `shared_example` with another example group, where we're not talking about a roulette, but about a bank account for instance?

```ruby
RSpec.shared_examples "a random number greater than 0" do
  it { expect(random_number).to be > 0 }
end

RSpec.describe "a roulette" do
  let(:random_number) { rand(1...10) }

  it_behaves_like "a random number greater than 0"
end

RSpec.describe "a bank account" do
  let(:balance) { 10_000 }

  it_behaves_like "a random number greater than 0" # the notion of 'random number' doesn't make sense here
end
```

The current state would then like me to do something like this (afaik):
```ruby
RSpec.shared_examples "a number greater than 0" do
  it { expect(number).to be > 0 }
end

RSpec.describe "a roulette" do
  let(:random_number) { rand(1...10) }

  it_behaves_like "a number greater than 0" do
    let(:number) { random_number }
  end
end

RSpec.describe "a bank account" do
  let(:balance) { 10_000 }

  it_behaves_like "a number greater than 0" do
    let(:number) { balance }
  end
end
```

And that's where I'm a little bit sad, because even if it works, it doesn't read as well as I would like to. I'd like to be able to pass the `random_number` or `balance` values directly to the shared part, without having to redefine them in the context of the example group. To make it clear, this last solution currently works, and is probably the best way to solve this problem **TODAY**, but I'm trying to find a way to make it less verbose and more readable.

Using `shared_expectations`, the solution would look like this:

```ruby
RSpec.shared_expectations "a number greater than 0" do
  expect(number).to be > 0
end

RSpec.describe "a roulette" do
  let(:random_number) { rand(1...10) }

  it { behaves_like "a number greater than 0", random_number }
end

RSpec.describe "a bank account" do
  let(:balance) { 10_000 }

  it { behaves_like "a number greater than 0", balance }
end
```

Once again, this is not a bug, but a feature request. I'm trying to find a way to pass the reference to `let` variables to some shared parts of the tests, without having to redefine them in the context of the example group.

I hope this clarifies the problem I'm trying to solve. Let me know if you have any other ideas on how to solve this problem!

**Comment by pirj** [comment]
> even if it works, it doesn't read as well as I would like to

Does this read well?

```
  it { behaves_like "a number greater than 0", balance }
```

What does “it” stand for? Is the word order similar to the English language?

I encountered cases where specs don’t read right.

The “it” usually refers to the subject under test. In your case, several implementations of something abstract, a number in your examples.

If you have shared example, it is supposed to operate on the abstract interface, something that those implementations have in common.

You are puzzled in your examples to find a common name for them.
I see no shame using a specific name from a specific example, and explicitly setting the abstract name and using it in the shared example.

I’m open to introduce new dsl to allow making specs more readable, especially if many existing specs suffer from problems like this. We have a corpus to analyse, under the umbrella of the real-world-rspec repo that gathered numerous open source projects using rspec.

I would strongly prefer if we had a real example to improve, even if its complexity is higher than examples you posted.

And a refactoring that would make those existing specs to read better with a simple touch. Eg https://github.com/rubocop/rubocop/pull/8447/files

Multiple extensions to RSpec exist, like saharspec, `its` etc.

Please provide a real public spec, and a refactoring PR that makes it read better with your suggestions.

**Comment by JonRowe** [comment]
:wave: It sounds to me like what you are describing here is matcher... e.g.

```
RSpec::Matchers.define :be_a_number_greater_than_zero do |expected|
  match { |number| number > 0 }
end

RSpec.describe "a roulette" do
  let(:random_number) { rand(1...10) }

  it { is_expected_.to be_a_number_greater_than_zero random_number }
end

RSpec.describe "a bank account" do
  let(:balance) { 10_000 }

  it { is_expected_.to be_a_number_greater_than_zero balance}
end
```

If your proposal is to run multiple examples from inside an example, that is not really possible, it would cause havoc with other things elsewhere, and your propose syntax doesn't solve the "lets aren't available outside of an example" so I'm going to close this as "not planned".

Realistically lets are never going to be available at a class level level (e.g when calling behaves_like) because it would allow mutuation between examples.

**Comment by francktrouillez** [comment]
@JonRowe

> It sounds to me like what you are describing here is matcher...

Indeed, I didn't consider them at all for this use case, but it looks like they already can be used to solve the problems I've been raising! Thanks for pointing this out. I've played a lot with shared examples, but not so much with matchers. I'll definitely look into this, thanks!

@pirj

Thanks for the answer! I was indeed missing something, as @JonRowe pointed out. Sorry for the confusion, and thanks for the help!

> Multiple extensions to RSpec exist, like saharspec, its etc.

Thanks for referencing these! I'll look into them, and see the different features they offer (and actually, why they're maybe not part of RSpec itself).


Once again, thanks for your help, and for your contributions to RSpec!
